include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.mocks.dart"
    - "build/**"
    - "coverage/**"
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_constructors_in_immutables: ignore
    constant_identifier_names: ignore
    use_key_in_widget_constructors: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    avoid_print: ignore
    sized_box_for_whitespace: ignore
    unnecessary_this: ignore
    prefer_interpolation_to_compose_strings: ignore
    sort_child_properties_last: ignore
    prefer_const_declarations: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_conditional_assignment: ignore
    annotate_overrides: ignore
    use_rethrow_when_possible: ignore
