name: tv
description: TV Series module for Ditonton app
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  bloc_test: ^9.1.7
  build_runner: ^2.0.4
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/circle-g.png
