// Mocks generated by Mockito 5.4.6 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i11;
import 'dart:convert' as _i34;
import 'dart:typed_data' as _i35;
import 'dart:ui' as _i32;

import 'package:core/common/failure.dart' as _i12;
import 'package:core/common/state_enum.dart' as _i31;
import 'package:core/data/datasources/db/database_helper.dart' as _i21;
import 'package:core/data/models/movie_table.dart' as _i23;
import 'package:core/data/models/tv_table.dart' as _i19;
import 'package:core/domain/entities/season_detail.dart' as _i15;
import 'package:core/domain/entities/tv.dart' as _i13;
import 'package:core/domain/entities/tv_detail.dart' as _i14;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;
import 'package:sqflite/sqflite.dart' as _i22;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i18;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i16;
import 'package:tv/data/models/season_detail_response.dart' as _i4;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_model.dart' as _i17;
import 'package:tv/domain/repositories/tv_repository.dart' as _i5;
import 'package:tv/domain/usecases/get_now_playing_tv.dart' as _i6;
import 'package:tv/domain/usecases/get_popular_tv.dart' as _i7;
import 'package:tv/domain/usecases/get_top_rated_tv.dart' as _i8;
import 'package:tv/domain/usecases/get_tv_detail.dart' as _i24;
import 'package:tv/domain/usecases/get_tv_recommendations.dart' as _i25;
import 'package:tv/domain/usecases/get_tv_season_detail.dart' as _i26;
import 'package:tv/domain/usecases/get_watchlist_tv.dart' as _i9;
import 'package:tv/domain/usecases/get_watchlist_tv_status.dart' as _i27;
import 'package:tv/domain/usecases/remove_watchlist_tv.dart' as _i29;
import 'package:tv/domain/usecases/save_watchlist_tv.dart' as _i28;
import 'package:tv/presentation/provider/tv_list_notifier.dart' as _i30;
import 'package:tv/presentation/provider/watchlist_tv_notifier.dart' as _i33;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvDetailResponse {
  _FakeTvDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonDetailResponse_2 extends _i1.SmartFake
    implements _i4.SeasonDetailResponse {
  _FakeSeasonDetailResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvRepository_3 extends _i1.SmartFake implements _i5.TvRepository {
  _FakeTvRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNowPlayingTv_4 extends _i1.SmartFake
    implements _i6.GetNowPlayingTv {
  _FakeGetNowPlayingTv_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularTv_5 extends _i1.SmartFake implements _i7.GetPopularTv {
  _FakeGetPopularTv_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTopRatedTv_6 extends _i1.SmartFake implements _i8.GetTopRatedTv {
  _FakeGetTopRatedTv_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTv_7 extends _i1.SmartFake
    implements _i9.GetWatchlistTv {
  _FakeGetWatchlistTv_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_8 extends _i1.SmartFake implements _i10.Response {
  _FakeResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_9 extends _i1.SmartFake
    implements _i10.StreamedResponse {
  _FakeStreamedResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i5.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getNowPlayingTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTv,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getNowPlayingTv,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getPopularTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTv,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getPopularTv,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getTopRatedTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTv,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getTopRatedTv,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>.value(
            _FakeEither_0<_i12.Failure, _i14.TvDetail>(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>> getTvSeasonDetail(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeasonDetail,
          [
            id,
            seasonNumber,
          ],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>>.value(
                _FakeEither_0<_i12.Failure, _i15.SeasonDetail>(
          this,
          Invocation.method(
            #getTvSeasonDetail,
            [
              id,
              seasonNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getTvRecommendations,
            [id],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> searchTv(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #searchTv,
            [query],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, String>> saveWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tv],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tv],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, String>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, String>> removeWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, String>>);

  @override
  _i11.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #getWatchlistTv,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i16.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i17.TvModel>> getNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTv,
          [],
        ),
        returnValue: _i11.Future<List<_i17.TvModel>>.value(<_i17.TvModel>[]),
      ) as _i11.Future<List<_i17.TvModel>>);

  @override
  _i11.Future<List<_i17.TvModel>> getPopularTv() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTv,
          [],
        ),
        returnValue: _i11.Future<List<_i17.TvModel>>.value(<_i17.TvModel>[]),
      ) as _i11.Future<List<_i17.TvModel>>);

  @override
  _i11.Future<List<_i17.TvModel>> getTopRatedTv() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTv,
          [],
        ),
        returnValue: _i11.Future<List<_i17.TvModel>>.value(<_i17.TvModel>[]),
      ) as _i11.Future<List<_i17.TvModel>>);

  @override
  _i11.Future<_i3.TvDetailResponse> getTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue:
            _i11.Future<_i3.TvDetailResponse>.value(_FakeTvDetailResponse_1(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i11.Future<_i3.TvDetailResponse>);

  @override
  _i11.Future<_i4.SeasonDetailResponse> getTvSeasonDetail(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeasonDetail,
          [
            id,
            seasonNumber,
          ],
        ),
        returnValue: _i11.Future<_i4.SeasonDetailResponse>.value(
            _FakeSeasonDetailResponse_2(
          this,
          Invocation.method(
            #getTvSeasonDetail,
            [
              id,
              seasonNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i4.SeasonDetailResponse>);

  @override
  _i11.Future<List<_i17.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i11.Future<List<_i17.TvModel>>.value(<_i17.TvModel>[]),
      ) as _i11.Future<List<_i17.TvModel>>);

  @override
  _i11.Future<List<_i17.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
        ),
        returnValue: _i11.Future<List<_i17.TvModel>>.value(<_i17.TvModel>[]),
      ) as _i11.Future<List<_i17.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i18.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<String> insertWatchlist(_i19.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tv],
        ),
        returnValue: _i11.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [tv],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> removeWatchlist(_i19.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i11.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i19.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i11.Future<_i19.TvTable?>.value(),
      ) as _i11.Future<_i19.TvTable?>);

  @override
  _i11.Future<List<_i19.TvTable>> getWatchlistTv() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i11.Future<List<_i19.TvTable>>.value(<_i19.TvTable>[]),
      ) as _i11.Future<List<_i19.TvTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i21.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i22.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i11.Future<_i22.Database?>.value(),
      ) as _i11.Future<_i22.Database?>);

  @override
  _i11.Future<int> insertWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<int> insertWatchlistTv(_i19.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistTv,
          [tv],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<int> removeWatchlist(_i23.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<int> removeWatchlistTv(_i19.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTv,
          [tv],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i11.Future<Map<String, dynamic>?>.value(),
      ) as _i11.Future<Map<String, dynamic>?>);

  @override
  _i11.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i11.Future<Map<String, dynamic>?>.value(),
      ) as _i11.Future<Map<String, dynamic>?>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i11.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GetNowPlayingTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingTv extends _i1.Mock implements _i6.GetNowPlayingTv {
  MockGetNowPlayingTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i7.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i8.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i24.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>.value(
            _FakeEither_0<_i12.Failure, _i14.TvDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i14.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i25.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [GetTvSeasonDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeasonDetail extends _i1.Mock implements _i26.GetTvSeasonDetail {
  MockGetTvSeasonDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>> execute(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            id,
            seasonNumber,
          ],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>>.value(
                _FakeEither_0<_i12.Failure, _i15.SeasonDetail>(
          this,
          Invocation.method(
            #execute,
            [
              id,
              seasonNumber,
            ],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, _i15.SeasonDetail>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i9.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>.value(
            _FakeEither_0<_i12.Failure, List<_i13.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Tv>>>);
}

/// A class which mocks [GetWatchlistTvStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvStatus extends _i1.Mock
    implements _i27.GetWatchlistTvStatus {
  MockGetWatchlistTvStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i28.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, String>> execute(_i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i29.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i11.Future<_i2.Either<_i12.Failure, String>> execute(_i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, String>>.value(
            _FakeEither_0<_i12.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, String>>);
}

/// A class which mocks [TvListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListNotifier extends _i1.Mock implements _i30.TvListNotifier {
  MockTvListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.Tv> get nowPlayingTv => (super.noSuchMethod(
        Invocation.getter(#nowPlayingTv),
        returnValue: <_i13.Tv>[],
      ) as List<_i13.Tv>);

  @override
  _i31.RequestState get nowPlayingState => (super.noSuchMethod(
        Invocation.getter(#nowPlayingState),
        returnValue: _i31.RequestState.Empty,
      ) as _i31.RequestState);

  @override
  List<_i13.Tv> get popularTv => (super.noSuchMethod(
        Invocation.getter(#popularTv),
        returnValue: <_i13.Tv>[],
      ) as List<_i13.Tv>);

  @override
  _i31.RequestState get popularTvState => (super.noSuchMethod(
        Invocation.getter(#popularTvState),
        returnValue: _i31.RequestState.Empty,
      ) as _i31.RequestState);

  @override
  List<_i13.Tv> get topRatedTv => (super.noSuchMethod(
        Invocation.getter(#topRatedTv),
        returnValue: <_i13.Tv>[],
      ) as List<_i13.Tv>);

  @override
  _i31.RequestState get topRatedTvState => (super.noSuchMethod(
        Invocation.getter(#topRatedTvState),
        returnValue: _i31.RequestState.Empty,
      ) as _i31.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  _i6.GetNowPlayingTv get getNowPlayingTv => (super.noSuchMethod(
        Invocation.getter(#getNowPlayingTv),
        returnValue: _FakeGetNowPlayingTv_4(
          this,
          Invocation.getter(#getNowPlayingTv),
        ),
      ) as _i6.GetNowPlayingTv);

  @override
  _i7.GetPopularTv get getPopularTv => (super.noSuchMethod(
        Invocation.getter(#getPopularTv),
        returnValue: _FakeGetPopularTv_5(
          this,
          Invocation.getter(#getPopularTv),
        ),
      ) as _i7.GetPopularTv);

  @override
  _i8.GetTopRatedTv get getTopRatedTv => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTv),
        returnValue: _FakeGetTopRatedTv_6(
          this,
          Invocation.getter(#getTopRatedTv),
        ),
      ) as _i8.GetTopRatedTv);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> fetchNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchNowPlayingTv,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> fetchPopularTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularTv,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> fetchTopRatedTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTv,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void addListener(_i32.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i32.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvNotifier extends _i1.Mock
    implements _i33.WatchlistTvNotifier {
  MockWatchlistTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.Tv> get watchlistTv => (super.noSuchMethod(
        Invocation.getter(#watchlistTv),
        returnValue: <_i13.Tv>[],
      ) as List<_i13.Tv>);

  @override
  _i31.RequestState get watchlistState => (super.noSuchMethod(
        Invocation.getter(#watchlistState),
        returnValue: _i31.RequestState.Empty,
      ) as _i31.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  _i9.GetWatchlistTv get getWatchlistTv => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTv),
        returnValue: _FakeGetWatchlistTv_7(
          this,
          Invocation.getter(#getWatchlistTv),
        ),
      ) as _i9.GetWatchlistTv);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> fetchWatchlistTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistTv,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void addListener(_i32.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i32.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i10.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i10.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i34.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i34.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i34.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<_i10.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i34.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i11.Future<_i10.Response>.value(_FakeResponse_8(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i11.Future<_i10.Response>);

  @override
  _i11.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<String>.value(_i20.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i35.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i11.Future<_i35.Uint8List>.value(_i35.Uint8List(0)),
      ) as _i11.Future<_i35.Uint8List>);

  @override
  _i11.Future<_i10.StreamedResponse> send(_i10.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i11.Future<_i10.StreamedResponse>.value(_FakeStreamedResponse_9(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i11.Future<_i10.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
