// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i24;
import 'dart:convert' as _i52;
import 'dart:typed_data' as _i53;
import 'dart:ui' as _i42;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i25;
import 'package:ditonton/common/state_enum.dart' as _i41;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i38;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i30;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i28;
import 'package:ditonton/data/datasources/tv_local_data_source.dart' as _i36;
import 'package:ditonton/data/datasources/tv_remote_data_source.dart' as _i34;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i29;
import 'package:ditonton/data/models/movie_table.dart' as _i31;
import 'package:ditonton/data/models/tv_detail_model.dart' as _i4;
import 'package:ditonton/data/models/tv_model.dart' as _i35;
import 'package:ditonton/data/models/tv_table.dart' as _i37;
import 'package:ditonton/domain/entities/movie.dart' as _i26;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i27;
import 'package:ditonton/domain/entities/tv.dart' as _i33;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i14;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i23;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i5;
import 'package:ditonton/domain/usecases/get_now_playing_movies.dart' as _i17;
import 'package:ditonton/domain/usecases/get_now_playing_tv.dart' as _i6;
import 'package:ditonton/domain/usecases/get_popular_movies.dart' as _i18;
import 'package:ditonton/domain/usecases/get_popular_tv.dart' as _i7;
import 'package:ditonton/domain/usecases/get_top_rated_movies.dart' as _i19;
import 'package:ditonton/domain/usecases/get_top_rated_tv.dart' as _i8;
import 'package:ditonton/domain/usecases/get_tv_detail.dart' as _i9;
import 'package:ditonton/domain/usecases/get_tv_recommendations.dart' as _i10;
import 'package:ditonton/domain/usecases/get_watchlist_movies.dart' as _i21;
import 'package:ditonton/domain/usecases/get_watchlist_tv.dart' as _i16;
import 'package:ditonton/domain/usecases/get_watchlist_tv_status.dart' as _i11;
import 'package:ditonton/domain/usecases/remove_watchlist_tv.dart' as _i13;
import 'package:ditonton/domain/usecases/save_watchlist_tv.dart' as _i12;
import 'package:ditonton/domain/usecases/search_movies.dart' as _i20;
import 'package:ditonton/domain/usecases/search_tv.dart' as _i15;
import 'package:ditonton/presentation/provider/movie_list_notifier.dart'
    as _i49;
import 'package:ditonton/presentation/provider/movie_search_notifier.dart'
    as _i50;
import 'package:ditonton/presentation/provider/now_playing_tv_notifier.dart'
    as _i46;
import 'package:ditonton/presentation/provider/popular_tv_notifier.dart'
    as _i44;
import 'package:ditonton/presentation/provider/top_rated_tv_notifier.dart'
    as _i45;
import 'package:ditonton/presentation/provider/tv_detail_notifier.dart' as _i43;
import 'package:ditonton/presentation/provider/tv_list_notifier.dart' as _i40;
import 'package:ditonton/presentation/provider/tv_search_notifier.dart' as _i47;
import 'package:ditonton/presentation/provider/watchlist_movie_notifier.dart'
    as _i51;
import 'package:ditonton/presentation/provider/watchlist_tv_notifier.dart'
    as _i48;
import 'package:http/http.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i32;
import 'package:sqflite/sqflite.dart' as _i39;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetailResponse_2 extends _i1.SmartFake
    implements _i4.TvDetailResponse {
  _FakeTvDetailResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvRepository_3 extends _i1.SmartFake implements _i5.TvRepository {
  _FakeTvRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNowPlayingTv_4 extends _i1.SmartFake
    implements _i6.GetNowPlayingTv {
  _FakeGetNowPlayingTv_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularTv_5 extends _i1.SmartFake implements _i7.GetPopularTv {
  _FakeGetPopularTv_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTopRatedTv_6 extends _i1.SmartFake implements _i8.GetTopRatedTv {
  _FakeGetTopRatedTv_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvDetail_7 extends _i1.SmartFake implements _i9.GetTvDetail {
  _FakeGetTvDetail_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTvRecommendations_8 extends _i1.SmartFake
    implements _i10.GetTvRecommendations {
  _FakeGetTvRecommendations_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTvStatus_9 extends _i1.SmartFake
    implements _i11.GetWatchlistTvStatus {
  _FakeGetWatchlistTvStatus_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSaveWatchlistTv_10 extends _i1.SmartFake
    implements _i12.SaveWatchlistTv {
  _FakeSaveWatchlistTv_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoveWatchlistTv_11 extends _i1.SmartFake
    implements _i13.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvDetail_12 extends _i1.SmartFake implements _i14.TvDetail {
  _FakeTvDetail_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchTv_13 extends _i1.SmartFake implements _i15.SearchTv {
  _FakeSearchTv_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTv_14 extends _i1.SmartFake
    implements _i16.GetWatchlistTv {
  _FakeGetWatchlistTv_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetNowPlayingMovies_15 extends _i1.SmartFake
    implements _i17.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularMovies_16 extends _i1.SmartFake
    implements _i18.GetPopularMovies {
  _FakeGetPopularMovies_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTopRatedMovies_17 extends _i1.SmartFake
    implements _i19.GetTopRatedMovies {
  _FakeGetTopRatedMovies_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchMovies_18 extends _i1.SmartFake implements _i20.SearchMovies {
  _FakeSearchMovies_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistMovies_19 extends _i1.SmartFake
    implements _i21.GetWatchlistMovies {
  _FakeGetWatchlistMovies_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_20 extends _i1.SmartFake implements _i22.Response {
  _FakeResponse_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_21 extends _i1.SmartFake
    implements _i22.StreamedResponse {
  _FakeStreamedResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i23.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue:
                _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                    _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, _i27.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i24.Future<_i2.Either<_i25.Failure, _i27.MovieDetail>>.value(
                _FakeEither_0<_i25.Failure, _i27.MovieDetail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, _i27.MovieDetail>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue:
                _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                    _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> saveWatchlist(
          _i27.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> removeWatchlist(
          _i27.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);

  @override
  _i24.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>
      getWatchlistMovies() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistMovies,
              [],
            ),
            returnValue:
                _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>.value(
                    _FakeEither_0<_i25.Failure, List<_i26.Movie>>(
              this,
              Invocation.method(
                #getWatchlistMovies,
                [],
              ),
            )),
          ) as _i24.Future<_i2.Either<_i25.Failure, List<_i26.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i28.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<List<_i29.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i24.Future<List<_i29.MovieModel>>.value(<_i29.MovieModel>[]),
      ) as _i24.Future<List<_i29.MovieModel>>);

  @override
  _i24.Future<List<_i29.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i24.Future<List<_i29.MovieModel>>.value(<_i29.MovieModel>[]),
      ) as _i24.Future<List<_i29.MovieModel>>);

  @override
  _i24.Future<List<_i29.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i24.Future<List<_i29.MovieModel>>.value(<_i29.MovieModel>[]),
      ) as _i24.Future<List<_i29.MovieModel>>);

  @override
  _i24.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i24.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i24.Future<_i3.MovieDetailResponse>);

  @override
  _i24.Future<List<_i29.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i24.Future<List<_i29.MovieModel>>.value(<_i29.MovieModel>[]),
      ) as _i24.Future<List<_i29.MovieModel>>);

  @override
  _i24.Future<List<_i29.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i24.Future<List<_i29.MovieModel>>.value(<_i29.MovieModel>[]),
      ) as _i24.Future<List<_i29.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i30.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<String> insertWatchlist(_i31.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<String>.value(_i32.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [movie],
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<String> removeWatchlist(_i31.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<String>.value(_i32.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<_i31.MovieTable?> getMovieById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i24.Future<_i31.MovieTable?>.value(),
      ) as _i24.Future<_i31.MovieTable?>);

  @override
  _i24.Future<List<_i31.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i24.Future<List<_i31.MovieTable>>.value(<_i31.MovieTable>[]),
      ) as _i24.Future<List<_i31.MovieTable>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i5.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> getNowPlayingTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTv,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #getNowPlayingTv,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> getPopularTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTv,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #getPopularTv,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> getTopRatedTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTv,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #getTopRatedTv,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>>.value(
            _FakeEither_0<_i25.Failure, _i14.TvDetail>(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #getTvRecommendations,
            [id],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> searchTv(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #searchTv,
            [query],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> saveWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tv],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> removeWatchlist(
          _i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);

  @override
  _i24.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #getWatchlistTv,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i34.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<List<_i35.TvModel>> getNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingTv,
          [],
        ),
        returnValue: _i24.Future<List<_i35.TvModel>>.value(<_i35.TvModel>[]),
      ) as _i24.Future<List<_i35.TvModel>>);

  @override
  _i24.Future<List<_i35.TvModel>> getPopularTv() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTv,
          [],
        ),
        returnValue: _i24.Future<List<_i35.TvModel>>.value(<_i35.TvModel>[]),
      ) as _i24.Future<List<_i35.TvModel>>);

  @override
  _i24.Future<List<_i35.TvModel>> getTopRatedTv() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTv,
          [],
        ),
        returnValue: _i24.Future<List<_i35.TvModel>>.value(<_i35.TvModel>[]),
      ) as _i24.Future<List<_i35.TvModel>>);

  @override
  _i24.Future<_i4.TvDetailResponse> getTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvDetail,
          [id],
        ),
        returnValue:
            _i24.Future<_i4.TvDetailResponse>.value(_FakeTvDetailResponse_2(
          this,
          Invocation.method(
            #getTvDetail,
            [id],
          ),
        )),
      ) as _i24.Future<_i4.TvDetailResponse>);

  @override
  _i24.Future<List<_i35.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvRecommendations,
          [id],
        ),
        returnValue: _i24.Future<List<_i35.TvModel>>.value(<_i35.TvModel>[]),
      ) as _i24.Future<List<_i35.TvModel>>);

  @override
  _i24.Future<List<_i35.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
        ),
        returnValue: _i24.Future<List<_i35.TvModel>>.value(<_i35.TvModel>[]),
      ) as _i24.Future<List<_i35.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i36.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<String> insertWatchlist(_i37.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<String>.value(_i32.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [tv],
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<String> removeWatchlist(_i37.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<String>.value(_i32.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<_i37.TvTable?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i24.Future<_i37.TvTable?>.value(),
      ) as _i24.Future<_i37.TvTable?>);

  @override
  _i24.Future<List<_i37.TvTable>> getWatchlistTv() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i24.Future<List<_i37.TvTable>>.value(<_i37.TvTable>[]),
      ) as _i24.Future<List<_i37.TvTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i38.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i39.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i24.Future<_i39.Database?>.value(),
      ) as _i24.Future<_i39.Database?>);

  @override
  _i24.Future<int> insertWatchlist(_i31.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<int> insertWatchlistTv(_i37.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistTv,
          [tv],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<int> removeWatchlist(_i31.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<int> removeWatchlistTv(_i37.TvTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTv,
          [tv],
        ),
        returnValue: _i24.Future<int>.value(0),
      ) as _i24.Future<int>);

  @override
  _i24.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i24.Future<Map<String, dynamic>?>.value(),
      ) as _i24.Future<Map<String, dynamic>?>);

  @override
  _i24.Future<Map<String, dynamic>?> getTvById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvById,
          [id],
        ),
        returnValue: _i24.Future<Map<String, dynamic>?>.value(),
      ) as _i24.Future<Map<String, dynamic>?>);

  @override
  _i24.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i24.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i24.Future<List<Map<String, dynamic>>>);

  @override
  _i24.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i24.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i24.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GetNowPlayingTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingTv extends _i1.Mock implements _i6.GetNowPlayingTv {
  MockGetNowPlayingTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i7.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i8.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i9.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>>.value(
            _FakeEither_0<_i25.Failure, _i14.TvDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, _i14.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i10.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [SearchTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTv extends _i1.Mock implements _i15.SearchTv {
  MockSearchTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [query],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [query],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i16.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>.value(
            _FakeEither_0<_i25.Failure, List<_i33.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, List<_i33.Tv>>>);
}

/// A class which mocks [GetWatchlistTvStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvStatus extends _i1.Mock
    implements _i11.GetWatchlistTvStatus {
  MockGetWatchlistTvStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i12.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> execute(_i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i13.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.TvRepository);

  @override
  _i24.Future<_i2.Either<_i25.Failure, String>> execute(_i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [tv],
        ),
        returnValue: _i24.Future<_i2.Either<_i25.Failure, String>>.value(
            _FakeEither_0<_i25.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [tv],
          ),
        )),
      ) as _i24.Future<_i2.Either<_i25.Failure, String>>);
}

/// A class which mocks [TvListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListNotifier extends _i1.Mock implements _i40.TvListNotifier {
  MockTvListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetNowPlayingTv get getNowPlayingTv => (super.noSuchMethod(
        Invocation.getter(#getNowPlayingTv),
        returnValue: _FakeGetNowPlayingTv_4(
          this,
          Invocation.getter(#getNowPlayingTv),
        ),
      ) as _i6.GetNowPlayingTv);

  @override
  _i7.GetPopularTv get getPopularTv => (super.noSuchMethod(
        Invocation.getter(#getPopularTv),
        returnValue: _FakeGetPopularTv_5(
          this,
          Invocation.getter(#getPopularTv),
        ),
      ) as _i7.GetPopularTv);

  @override
  _i8.GetTopRatedTv get getTopRatedTv => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTv),
        returnValue: _FakeGetTopRatedTv_6(
          this,
          Invocation.getter(#getTopRatedTv),
        ),
      ) as _i8.GetTopRatedTv);

  @override
  List<_i33.Tv> get nowPlayingTv => (super.noSuchMethod(
        Invocation.getter(#nowPlayingTv),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  _i41.RequestState get nowPlayingState => (super.noSuchMethod(
        Invocation.getter(#nowPlayingState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get popularTv => (super.noSuchMethod(
        Invocation.getter(#popularTv),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  _i41.RequestState get popularTvState => (super.noSuchMethod(
        Invocation.getter(#popularTvState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get topRatedTv => (super.noSuchMethod(
        Invocation.getter(#topRatedTv),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  _i41.RequestState get topRatedTvState => (super.noSuchMethod(
        Invocation.getter(#topRatedTvState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchNowPlayingTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> fetchPopularTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> fetchTopRatedTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailNotifier extends _i1.Mock implements _i43.TvDetailNotifier {
  MockTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.GetTvDetail get getTvDetail => (super.noSuchMethod(
        Invocation.getter(#getTvDetail),
        returnValue: _FakeGetTvDetail_7(
          this,
          Invocation.getter(#getTvDetail),
        ),
      ) as _i9.GetTvDetail);

  @override
  _i10.GetTvRecommendations get getTvRecommendations => (super.noSuchMethod(
        Invocation.getter(#getTvRecommendations),
        returnValue: _FakeGetTvRecommendations_8(
          this,
          Invocation.getter(#getTvRecommendations),
        ),
      ) as _i10.GetTvRecommendations);

  @override
  _i11.GetWatchlistTvStatus get getWatchListStatus => (super.noSuchMethod(
        Invocation.getter(#getWatchListStatus),
        returnValue: _FakeGetWatchlistTvStatus_9(
          this,
          Invocation.getter(#getWatchListStatus),
        ),
      ) as _i11.GetWatchlistTvStatus);

  @override
  _i12.SaveWatchlistTv get saveWatchlist => (super.noSuchMethod(
        Invocation.getter(#saveWatchlist),
        returnValue: _FakeSaveWatchlistTv_10(
          this,
          Invocation.getter(#saveWatchlist),
        ),
      ) as _i12.SaveWatchlistTv);

  @override
  _i13.RemoveWatchlistTv get removeWatchlist => (super.noSuchMethod(
        Invocation.getter(#removeWatchlist),
        returnValue: _FakeRemoveWatchlistTv_11(
          this,
          Invocation.getter(#removeWatchlist),
        ),
      ) as _i13.RemoveWatchlistTv);

  @override
  _i14.TvDetail get tv => (super.noSuchMethod(
        Invocation.getter(#tv),
        returnValue: _FakeTvDetail_12(
          this,
          Invocation.getter(#tv),
        ),
      ) as _i14.TvDetail);

  @override
  _i41.RequestState get tvState => (super.noSuchMethod(
        Invocation.getter(#tvState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get tvRecommendations => (super.noSuchMethod(
        Invocation.getter(#tvRecommendations),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  _i41.RequestState get recommendationState => (super.noSuchMethod(
        Invocation.getter(#recommendationState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
        Invocation.getter(#isAddedToWatchlist),
        returnValue: false,
      ) as bool);

  @override
  String get watchlistMessage => (super.noSuchMethod(
        Invocation.getter(#watchlistMessage),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#watchlistMessage),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchTvDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvDetail,
          [id],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> addWatchlist(_i14.TvDetail? tv) => (super.noSuchMethod(
        Invocation.method(
          #addWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> removeFromWatchlist(_i14.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [tv],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadWatchlistStatus,
          [id],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PopularTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvNotifier extends _i1.Mock implements _i44.PopularTvNotifier {
  MockPopularTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetPopularTv get getPopularTv => (super.noSuchMethod(
        Invocation.getter(#getPopularTv),
        returnValue: _FakeGetPopularTv_5(
          this,
          Invocation.getter(#getPopularTv),
        ),
      ) as _i7.GetPopularTv);

  @override
  _i41.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get tvs => (super.noSuchMethod(
        Invocation.getter(#tvs),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchPopularTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TopRatedTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvNotifier extends _i1.Mock
    implements _i45.TopRatedTvNotifier {
  MockTopRatedTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTopRatedTv get getTopRatedTv => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTv),
        returnValue: _FakeGetTopRatedTv_6(
          this,
          Invocation.getter(#getTopRatedTv),
        ),
      ) as _i8.GetTopRatedTv);

  @override
  _i41.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get tvs => (super.noSuchMethod(
        Invocation.getter(#tvs),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchTopRatedTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [NowPlayingTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNowPlayingTvNotifier extends _i1.Mock
    implements _i46.NowPlayingTvNotifier {
  MockNowPlayingTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetNowPlayingTv get getNowPlayingTv => (super.noSuchMethod(
        Invocation.getter(#getNowPlayingTv),
        returnValue: _FakeGetNowPlayingTv_4(
          this,
          Invocation.getter(#getNowPlayingTv),
        ),
      ) as _i6.GetNowPlayingTv);

  @override
  _i41.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get tvs => (super.noSuchMethod(
        Invocation.getter(#tvs),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchNowPlayingTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchNowPlayingTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TvSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSearchNotifier extends _i1.Mock implements _i47.TvSearchNotifier {
  MockTvSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.SearchTv get searchTv => (super.noSuchMethod(
        Invocation.getter(#searchTv),
        returnValue: _FakeSearchTv_13(
          this,
          Invocation.getter(#searchTv),
        ),
      ) as _i15.SearchTv);

  @override
  _i41.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i33.Tv> get searchResult => (super.noSuchMethod(
        Invocation.getter(#searchResult),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchTvSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #fetchTvSearch,
          [query],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvNotifier extends _i1.Mock
    implements _i48.WatchlistTvNotifier {
  MockWatchlistTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.GetWatchlistTv get getWatchlistTv => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTv),
        returnValue: _FakeGetWatchlistTv_14(
          this,
          Invocation.getter(#getWatchlistTv),
        ),
      ) as _i16.GetWatchlistTv);

  @override
  List<_i33.Tv> get watchlistTv => (super.noSuchMethod(
        Invocation.getter(#watchlistTv),
        returnValue: <_i33.Tv>[],
      ) as List<_i33.Tv>);

  @override
  _i41.RequestState get watchlistState => (super.noSuchMethod(
        Invocation.getter(#watchlistState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchWatchlistTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistTv,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MovieListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListNotifier extends _i1.Mock implements _i49.MovieListNotifier {
  MockMovieListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.GetNowPlayingMovies get getNowPlayingMovies => (super.noSuchMethod(
        Invocation.getter(#getNowPlayingMovies),
        returnValue: _FakeGetNowPlayingMovies_15(
          this,
          Invocation.getter(#getNowPlayingMovies),
        ),
      ) as _i17.GetNowPlayingMovies);

  @override
  _i18.GetPopularMovies get getPopularMovies => (super.noSuchMethod(
        Invocation.getter(#getPopularMovies),
        returnValue: _FakeGetPopularMovies_16(
          this,
          Invocation.getter(#getPopularMovies),
        ),
      ) as _i18.GetPopularMovies);

  @override
  _i19.GetTopRatedMovies get getTopRatedMovies => (super.noSuchMethod(
        Invocation.getter(#getTopRatedMovies),
        returnValue: _FakeGetTopRatedMovies_17(
          this,
          Invocation.getter(#getTopRatedMovies),
        ),
      ) as _i19.GetTopRatedMovies);

  @override
  List<_i26.Movie> get nowPlayingMovies => (super.noSuchMethod(
        Invocation.getter(#nowPlayingMovies),
        returnValue: <_i26.Movie>[],
      ) as List<_i26.Movie>);

  @override
  _i41.RequestState get nowPlayingState => (super.noSuchMethod(
        Invocation.getter(#nowPlayingState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i26.Movie> get popularMovies => (super.noSuchMethod(
        Invocation.getter(#popularMovies),
        returnValue: <_i26.Movie>[],
      ) as List<_i26.Movie>);

  @override
  _i41.RequestState get popularMoviesState => (super.noSuchMethod(
        Invocation.getter(#popularMoviesState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i26.Movie> get topRatedMovies => (super.noSuchMethod(
        Invocation.getter(#topRatedMovies),
        returnValue: <_i26.Movie>[],
      ) as List<_i26.Movie>);

  @override
  _i41.RequestState get topRatedMoviesState => (super.noSuchMethod(
        Invocation.getter(#topRatedMoviesState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchNowPlayingMovies() => (super.noSuchMethod(
        Invocation.method(
          #fetchNowPlayingMovies,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> fetchPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularMovies,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> fetchTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedMovies,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MovieSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchNotifier extends _i1.Mock
    implements _i50.MovieSearchNotifier {
  MockMovieSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.SearchMovies get searchMovies => (super.noSuchMethod(
        Invocation.getter(#searchMovies),
        returnValue: _FakeSearchMovies_18(
          this,
          Invocation.getter(#searchMovies),
        ),
      ) as _i20.SearchMovies);

  @override
  _i41.RequestState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  List<_i26.Movie> get searchResult => (super.noSuchMethod(
        Invocation.getter(#searchResult),
        returnValue: <_i26.Movie>[],
      ) as List<_i26.Movie>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchMovieSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #fetchMovieSearch,
          [query],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistMovieNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMovieNotifier extends _i1.Mock
    implements _i51.WatchlistMovieNotifier {
  MockWatchlistMovieNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.GetWatchlistMovies get getWatchlistMovies => (super.noSuchMethod(
        Invocation.getter(#getWatchlistMovies),
        returnValue: _FakeGetWatchlistMovies_19(
          this,
          Invocation.getter(#getWatchlistMovies),
        ),
      ) as _i21.GetWatchlistMovies);

  @override
  List<_i26.Movie> get watchlistMovies => (super.noSuchMethod(
        Invocation.getter(#watchlistMovies),
        returnValue: <_i26.Movie>[],
      ) as List<_i26.Movie>);

  @override
  _i41.RequestState get watchlistState => (super.noSuchMethod(
        Invocation.getter(#watchlistState),
        returnValue: _i41.RequestState.Empty,
      ) as _i41.RequestState);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i32.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> fetchWatchlistMovies() => (super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistMovies,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void addListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i42.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i22.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Future<_i22.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<_i22.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<_i22.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i52.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<_i22.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i52.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<_i22.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i52.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<_i22.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i52.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i24.Future<_i22.Response>.value(_FakeResponse_20(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i24.Future<_i22.Response>);

  @override
  _i24.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<String>.value(_i32.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i24.Future<String>);

  @override
  _i24.Future<_i53.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i24.Future<_i53.Uint8List>.value(_i53.Uint8List(0)),
      ) as _i24.Future<_i53.Uint8List>);

  @override
  _i24.Future<_i22.StreamedResponse> send(_i22.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i24.Future<_i22.StreamedResponse>.value(_FakeStreamedResponse_21(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i24.Future<_i22.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
